services:
  server:
    restart: always
    build:
      context: .
      target: final
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - GUILD_ID=${GUILD_ID}
      - OLLAMA_URL=${OLLAMA_URL}
      - OLLAMA_MODEL=${OLLAMA_MODEL}
      - RESPOND_TO_ALL_MESSAGES=${RESPOND_TO_ALL_MESSAGES}
      - RESPONDS_TO=${RESPONDS_TO}
      - MAX_STORED_MESSAGES=${MAX_STORED_MESSAGES}
      - LOGGER_DEBUG=${LOGGER_DEBUG}
      - WRITE_LOGS=${WRITE_LOGS}
    volumes:
      - data:/out_data
volumes:
  data:
