name: Rust Build and Release

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust
      run: rustup update stable

    - name: Build
      run: cargo build --release --verbose

    - name: Run tests
      run: cargo test --verbose

    - name: Create release artifact
      run: |
        mkdir artifacts
        cp target/release/dolly_parton artifacts/

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: release-binary
        path: artifacts/

  windows-build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust
      run: rustup update stable

    - name: Build
      run: cargo build --release --verbose

    - name: Run tests
      run: cargo test --verbose

    - name: Create release artifact
      run: |
        mkdir artifacts
        cp target/release/dolly_parton.exe artifacts/

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: release-binary-windows
        path: artifacts/

  release:
    runs-on: ubuntu-latest
    needs: [build, windows-build]

    steps:
    - uses: actions/checkout@v4

    - name: Download Linux artifact
      uses: actions/download-artifact@v4
      with:
        name: release-binary
        path: ./release-binary-linux

    - name: Download Windows artifact
      uses: actions/download-artifact@v4
      with:
        name: release-binary-windows
        path: ./release-binary-windows

    - name: Install GitHub CLI
      run: sudo apt-get install -y gh

    - name: Authenticate with GitHub CLI
      run: gh auth login --with-token <<< "${{ secrets.GITHUB_TOKEN }}"

    - name: Create GitHub Release
      run: |
        gh release create v${{ github.run_number }} ./release-binary-linux/dolly_parton ./release-binary-windows/dolly_parton.exe \
          --title "Release ${{ github.run_number }}" \
          --notes "Automated release"

    - name: Upload Release Asset
      run: gh release upload v${{ github.run_number }} ./release-binary/dolly_parton ./release-binary-windows/dolly_parton.exe
